version: '3.8'

services:
  fuzzer0:
    build: .
    container_name: fuzzer-master
    privileged: true
    restart: unless-stopped
    volumes:
      - /data:/data
    command: >
      sh -c "afl-fuzz -t 1000 -i /data/seeds_min -o /data/afl-output -M fuzzer0 -x /data/dict/nsf.dict -- /fuzzing/harness @@"

  fuzzer1:
    build: .
    container_name: fuzzer-slave1
    privileged: true
    restart: unless-stopped
    volumes:
      - /data:/data
    depends_on:
      - fuzzer0
    command: >
      sh -c "sleep 5 && afl-fuzz -t 1000 -i /data/seeds_min -o /data/afl-output -S fuzzer1 -x /data/dict/nsf.dict -- /fuzzing/harness @@"

  fuzzer2:
    build: .
    container_name: fuzzer-slave2
    privileged: true
    restart: unless-stopped
    volumes:
      - /data:/data
    depends_on:
      - fuzzer0
    command: >
      sh -c "sleep 5 && afl-fuzz -t 1000 -i /data/seeds_min -o /data/afl-output -S fuzzer2 -x /data/dict/nsf.dict -- /fuzzing/harness @@"

  fuzzer3:
    build: .
    container_name: fuzzer-slave3
    privileged: true
    restart: unless-stopped
    volumes:
      - /data:/data
    depends_on:
      - fuzzer0
    command: >
      sh -c "sleep 5 && afl-fuzz -t 1000 -i /data/seeds_min -o /data/afl-output -S fuzzer3 -x /data/dict/nsf.dict -- /fuzzing/harness @@"

  postgres:
    image: postgres:16-alpine
    container_name: fuzzer-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fuzzer
      POSTGRES_PASSWORD: XItyYpPDg8y3hHtzipBSX2ZHAVZZA2q_
      POSTGRES_DB: fuzzer_db
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
