name: Deploy to Oracle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 79.72.66.118
          username: opc
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            if [ -d ~/fuzzer-pipeline ]; then
              cd ~/fuzzer-pipeline && git pull origin main
            else
              git clone https://github.com/r4xis/fuzzer-pipeline.git ~/fuzzer-pipeline
              cd ~/fuzzer-pipeline
            fi
            docker build -t fuzzer-pipeline .
            docker run --rm fuzzer-pipeline
